context:
  name: wsp-balsa
  git_repo_url: https://github.com/wsp-sag/balsa
  latest_tag: ${{ git.latest_tag( git_repo_url ) }}

package:
  name: ${{ name }}
  version: ${{ latest_tag }}

source:
  git: ${{ git_repo_url }}
  tag: ${{ latest_tag }}

build:
  noarch: python
  script: pip install . -v

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools >=64
    - setuptools-scm >=8
  run:
    - python >=3.7
    - pandas >=0.24
    - numpy >=1.21
    - numexpr >=2.6

about:
  homepage: ${{ git_repo_url }}
  license: MIT
  license_file: LICENSE
  summary: Python tools for travel demand forecasting applications and analyses
