package:
  name: wsp-balsa
  version: "1.1.0"

source:
  path: ../

build:
  number: auto
  noarch: python

requirements:
  build:
    - python
    - setuptools
  run:
    - pandas >=0.21
    - numpy >=1.15
    - numba >=0.35
    - numexpr >=2.6
    - six >=1.10
    - matplotlib >=3.0

about:
  home: https://github.com/wsp-sag/balsa
  summary: A collection of Python functions and tools to facilitate travel demand forecasting applications and analyses
