{% set data = load_setup_py_data() %}

package:
  name: wsp-balsa
  version: {{ data.get('version') }}

source:
  path: ../

build:
  noarch: python
  script: python setup.py --quiet install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python
  run:
    - python >=3.7
    - pandas >=0.21
    - numpy >=1.15
    - numba >=0.35
    - numexpr >=2.6
    - matplotlib >=3.0
    - openmatrix

about:
  home: https://github.com/wsp-sag/balsa
  license: MIT
  license_file: LICENSE
  summary: Python tools for travel demand forecasting applications and analyses

extra:
  maintainers:
    - Brian Cheung
    - Peter Kucirek
