{% set data = load_setup_py_data() %}

package:
  name: wsp-balsa
  version: {{ data.get('version') }}

source:
  path: ../

build:
  number: auto
  noarch: python

requirements:
  host:
    - python
  run:
    - python
    - pandas >=0.21
    - numpy >=1.15
    - numba >=0.35
    - numexpr >=2.6

about:
  home: https://github.com/wsp-sag/balsa
  license: MIT
  summary: Python tools for travel demand forecasting applications and analyses

extra:
  maintainers:
    - Brian Cheung
    - Peter Kucirek
